# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
matchItems=enchanted_book
stackSize=1-64
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
tile=lure
enchantmentIDs=lure