# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
source=/textures/environment/rain_clouds.png
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
weather=rain thunder
blend=screen
rotate=true
axis=0.0 -1.0 0.0