# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
startFadeIn=18:00
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
endFadeIn=18:30
# suppress inspection "UnusedProperty"
startFadeOut=18:30
endFadeOut=20:00
axis=0.0 1.1 0.0
# suppress inspection "UnusedProperty"
source=/textures/environment/cloud2.png