# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
source=/textures/environment/rain_clouds.png
# suppress inspection "UnusedProperty"
weather=rain thunder
# suppress inspection "UnusedProperty"
blend=screen
rotate=true
axis=0.0 0.2 0.0