# suppress inspection "UnusedProperty"
startFadeIn=5:30
# suppress inspection "UnusedProperty"
endFadeIn=6:00
# suppress inspection "UnusedProperty"
startFadeOut=17:50
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
endFadeOut=18:40
blend=screen
source=/textures/environment/sun_glow.png