# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
startFadeIn=18:10
endFadeIn=18:40
startFadeOut=5:00
endFadeOut=5:30
blend=screen
# suppress inspection "UnusedProperty"
rotate=true
source=/textures/environment/starfield01.png