# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
startFadeIn=17:50
endFadeIn=18:30
endFadeOut=19:20
blend=screen
rotate=true
source=/textures/environment/sky_sunflare.png