# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
startFadeIn=4:40
# suppress inspection "UnusedProperty"
endFadeIn=5:00
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
endFadeOut=5:50
# suppress inspection "UnusedProperty"
blend=screen
rotate=true
source=/textures/environment/sky_sunflare.png