biomes=FrozenOcean FrozenRiver SnowyTundra SnowyMountains SnowyBeach SnowyTaiga SnowyTaigaHills IceSpikes SnowyTaigaMountains Mountains WoodedMountains deep_frozen_ocean snowy_plains ice_spikes grove snowy_slopes frozen_peaks jagged_peaks
startFadeIn=18:00
endFadeIn=20:00
endFadeOut=4:00
blend=screen
rotate=false
source=/textures/environment/northernlight.png
