# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
startFadeIn=03:45
endFadeIn=03:46
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
endFadeOut=03:50
blend=screen
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
rotate=true
axis=1.0 0.0 1.0
speed=180.0
source=/textures/environment/starfieldshootingstar1.png