# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
matchItems=enchanted_book
# suppress inspection "UnusedProperty"
stackSize=1-64
tile=looting
# suppress inspection "UnusedProperty"
enchantmentIDs=looting