# suppress inspection "UnusedProperty"
matchItems=enchanted_book
# suppress inspection "UnusedProperty"
stackSize=1-64
# suppress inspection "UnusedProperty"
tile=curse_of_vanishing
# suppress inspection "UnusedProperty"
enchantmentIDs=vanishing_curse