#cold
# suppress inspection "UnusedProperty"
skins.1=2
# suppress inspection "UnusedProperty"
biomes.1=SnowyPlains IceSpikes SnowyTaiga Grove SnowySlopes FrozenPeaks JaggedPeaks SnowyBeach FrozenOcean DeepFrozenOcean

#cool
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
skins.2=3
# suppress inspection "UnusedProperty"
biomes.2=OldGrowthPineTaiga OldGrowthSpruceTaiga Taiga WindsweptHills WindsweptGravellyHills WindsweptForest StonyPeaks StonyShore ColdOcean DeepColdOcean

#warm
# suppress inspection "UnusedProperty"
skins.3=4
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
biomes.3=Plains SunflowerPlains Forest FlowerForest BirchForest DarkForest OldGrowthBirchForest Meadow CherryGrove Beach Ocean DeepOcean MushroomFields

# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
#wetlands
# suppress inspection "UnusedProperty"
skins.4=5
biomes.4=Swamp MangroveSwamp Jungle SparseJungle BambooJungle LukewarmOcean DeepLukewarmOcean

# suppress inspection "UnusedProperty"
#very warm
skins.5=6
biomes.5=Savanna SavannaPlateau WindsweptSavanna WarmOcean

#hot
skins.6=7
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
biomes.6=Desert Badlands ErodedBadlands WoodedBadlands

#end
skins.7=8
biomes.7=TheEnd EndHighlands EndMidlands SmallEndIslands EndBarrens

#nether
skins.8=9
biomes.8=NetherWastes WarpedForest CrimsonForest SoulSandValley BasaltDeltas

skins.9=10

skins.10=11
biomes.10=Desert DesertHills DesertLakes Badlands ErodedBadlands BadlandsPlateau ModifiedBadlandsPlateau WoodedBadlandsPlateau ModifiedWoodedBadlandsPlateau Savanna