# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
matchItems=enchanted_book
stackSize=1-64
# suppress inspection "UnusedProperty"
tile=silk_touch
# suppress inspection "UnusedProperty"
enchantmentIDs=silk_touch