# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
matchItems=enchanted_book
# suppress inspection "UnusedProperty"
stackSize=1-64
tile=frost_walker
# suppress inspection "UnusedProperty"
enchantmentIDs=frost_walker