# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
matchItems=enchanted_book
# suppress inspection "UnusedProperty"
stackSize=1-64
tile=bane_of_arthropods
enchantmentIDs=bane_of_arthropods