package com.otterly76.ott.block;

import com.otterly76.ott.crop.HedgeSprouts;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.state.BlockBehaviour.Properties;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.registries.DeferredRegister;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.function.Consumer;
import java.util.function.Function;

import static com.otterly76.ott.Constants.MOD_ID;

@SuppressWarnings("MismatchedQueryAndUpdateOfCollection")

public class ModBlocks {
    public static final DeferredRegister.Blocks BLOCKS = DeferredRegister.createBlocks(MOD_ID);

    public static final List<DeferredBlock<? extends IGradientBlock>> ALL_GRADIENT_BLOCKS = new ArrayList<>();

    private static final List<DeferredBlock<? extends IGradientBlock>> ALL_CONCRETE_BLOCKS = new ArrayList<>();
    private static final List<DeferredBlock<? extends IGradientBlock>> ALL_TERRACOTTA_BLOCKS = new ArrayList<>();
    private static final List<DeferredBlock<? extends IGradientBlock>> ALL_WOOL_BLOCKS = new ArrayList<>();
    private static final List<DeferredBlock<? extends IGradientBlock>> ALL_STAINED_GLASS_BLOCKS = new ArrayList<>();
    private static final List<DeferredBlock<? extends IGradientBlock>> ALL_CONCRETE_POWDER_BLOCKS = new ArrayList<>();

    public static final List<DeferredBlock<? extends Block>> LEAVES = new ArrayList<>();
    public static final List<DeferredBlock<? extends Block>> SEAGLASS = new ArrayList<>();
    public static final List<DeferredBlock<? extends Block>> LIMESTONE = new ArrayList<>();
    public static final List<DeferredBlock<? extends Block>> TESTBLOCK = new ArrayList<>();

    private static <T extends Block> DeferredBlock<T> registerTestblock(String name, java.util.function.Supplier<T> block) {
        DeferredBlock<T> ret = BLOCKS.register(name, block);
        TESTBLOCK.add(ret);
        return ret;
    }

    // Some testblocks for testing purposes
    public static final DeferredBlock<Block> TESTBLOCK_00 = BLOCKS.register("testblock_00", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> TESTBLOCK_01 = BLOCKS.register("testblock_01", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> TESTBLOCK_02 = BLOCKS.register("testblock_02", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> TESTBLOCK_03 = BLOCKS.register("testblock_03", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> TESTBLOCK_10 = BLOCKS.register("testblock_10", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> TESTBLOCK_11 = BLOCKS.register("testblock_11", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> TESTBLOCK_12 = BLOCKS.register("testblock_12", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> TESTBLOCK_13 = BLOCKS.register("testblock_13", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> TESTBLOCK_20 = BLOCKS.register("testblock_20", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> TESTBLOCK_21 = BLOCKS.register("testblock_21", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> TESTBLOCK_22 = BLOCKS.register("testblock_22", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> TESTBLOCK_23 = BLOCKS.register("testblock_23", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> TESTBLOCK_30 = BLOCKS.register("testblock_30", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> TESTBLOCK_31 = BLOCKS.register("testblock_31", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> TESTBLOCK_32 = BLOCKS.register("testblock_32", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> TESTBLOCK_33 = BLOCKS.register("testblock_33", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));

    private static <T extends Block> DeferredBlock<T> registerLimestone(String name, java.util.function.Supplier<T> block) {
        DeferredBlock<T> ret = BLOCKS.register(name, block);
        LIMESTONE.add(ret);
        return ret;
    }

    // Static limestone blocks since I have no idea what Ray is planning
    public static final DeferredBlock<Block> LIMESTONE_00 = BLOCKS.register("limestone_00", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> LIMESTONE_01 = BLOCKS.register("limestone_01", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> LIMESTONE_02 = BLOCKS.register("limestone_02", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> LIMESTONE_03 = BLOCKS.register("limestone_03", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> LIMESTONE_10 = BLOCKS.register("limestone_10", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> LIMESTONE_11 = BLOCKS.register("limestone_11", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> LIMESTONE_12 = BLOCKS.register("limestone_12", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> LIMESTONE_13 = BLOCKS.register("limestone_13", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> LIMESTONE_20 = BLOCKS.register("limestone_20", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> LIMESTONE_21 = BLOCKS.register("limestone_21", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> LIMESTONE_22 = BLOCKS.register("limestone_22", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> LIMESTONE_23 = BLOCKS.register("limestone_23", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> LIMESTONE_30 = BLOCKS.register("limestone_30", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> LIMESTONE_31 = BLOCKS.register("limestone_31", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> LIMESTONE_32 = BLOCKS.register("limestone_32", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));
    public static final DeferredBlock<Block> LIMESTONE_33 = BLOCKS.register("limestone_33", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE)));

    private static <T extends Block> DeferredBlock<T> registerSeaglass(String name, java.util.function.Supplier<T> block) {
        DeferredBlock<T> ret = BLOCKS.register(name, block);
        SEAGLASS.add(ret);
        return ret;
    }

    // Wheee Seaglass
    public static final DeferredBlock<Block> BLACK_BUBBLES_SEAGLASS = BLOCKS.register("black_bubbles_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> BLACK_SEAGLASS = BLOCKS.register("black_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> BLACK_SMOOTH_SEAGLASS = BLOCKS.register("black_smooth_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> BLACK_WAVES_SEAGLASS = BLOCKS.register("black_waves_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> BLUE_BUBBLES_SEAGLASS = BLOCKS.register("blue_bubbles_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> BLUE_SEAGLASS = BLOCKS.register("blue_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> BLUE_SMOOTH_SEAGLASS = BLOCKS.register("blue_smooth_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> BLUE_WAVES_SEAGLASS = BLOCKS.register("blue_waves_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> BROWN_BUBBLES_SEAGLASS = BLOCKS.register("brown_bubbles_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> BROWN_SEAGLASS = BLOCKS.register("brown_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> BROWN_SMOOTH_SEAGLASS = BLOCKS.register("brown_smooth_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> BROWN_WAVES_SEAGLASS = BLOCKS.register("brown_waves_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> CYAN_BUBBLES_SEAGLASS = BLOCKS.register("cyan_bubbles_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> CYAN_SEAGLASS = BLOCKS.register("cyan_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> CYAN_SMOOTH_SEAGLASS = BLOCKS.register("cyan_smooth_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> CYAN_WAVES_SEAGLASS = BLOCKS.register("cyan_waves_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> ETHEREAL1_BUBBLES_SEAGLASS = BLOCKS.register("ethereal1_bubbles_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> ETHEREAL1_SEAGLASS = BLOCKS.register("ethereal1_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> ETHEREAL1_SMOOTH_SEAGLASS = BLOCKS.register("ethereal1_smooth_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> ETHEREAL1_WAVES_SEAGLASS = BLOCKS.register("ethereal1_waves_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> ETHEREAL2_BUBBLES_SEAGLASS = BLOCKS.register("ethereal2_bubbles_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> ETHEREAL2_SEAGLASS = BLOCKS.register("ethereal2_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> ETHEREAL2_SMOOTH_SEAGLASS = BLOCKS.register("ethereal2_smooth_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> ETHEREAL2_WAVES_SEAGLASS = BLOCKS.register("ethereal2_waves_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> ETHEREAL3_BUBBLES_SEAGLASS = BLOCKS.register("ethereal3_bubbles_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> ETHEREAL3_SEAGLASS = BLOCKS.register("ethereal3_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> ETHEREAL3_SMOOTH_SEAGLASS = BLOCKS.register("ethereal3_smooth_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> ETHEREAL3_WAVES_SEAGLASS = BLOCKS.register("ethereal3_waves_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> ETHEREAL4_BUBBLES_SEAGLASS = BLOCKS.register("ethereal4_bubbles_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> ETHEREAL4_SEAGLASS = BLOCKS.register("ethereal4_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> ETHEREAL4_SMOOTH_SEAGLASS = BLOCKS.register("ethereal4_smooth_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> ETHEREAL4_WAVES_SEAGLASS = BLOCKS.register("ethereal4_waves_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> GRAY_BUBBLES_SEAGLASS = BLOCKS.register("gray_bubbles_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> GRAY_SEAGLASS = BLOCKS.register("gray_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> GRAY_SMOOTH_SEAGLASS = BLOCKS.register("gray_smooth_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> GRAY_WAVES_SEAGLASS = BLOCKS.register("gray_waves_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> GREEN_BUBBLES_SEAGLASS = BLOCKS.register("green_bubbles_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> GREEN_SEAGLASS = BLOCKS.register("green_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> GREEN_SMOOTH_SEAGLASS = BLOCKS.register("green_smooth_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> GREEN_WAVES_SEAGLASS = BLOCKS.register("green_waves_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> LIGHT_BLUE_BUBBLES_SEAGLASS = BLOCKS.register("light_blue_bubbles_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> LIGHT_BLUE_SEAGLASS = BLOCKS.register("light_blue_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> LIGHT_BLUE_SMOOTH_SEAGLASS = BLOCKS.register("light_blue_smooth_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> LIGHT_BLUE_WAVES_SEAGLASS = BLOCKS.register("light_blue_waves_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> LIGHT_GRAY_BUBBLES_SEAGLASS = BLOCKS.register("light_gray_bubbles_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> LIGHT_GRAY_SEAGLASS = BLOCKS.register("light_gray_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> LIGHT_GRAY_SMOOTH_SEAGLASS = BLOCKS.register("light_gray_smooth_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> LIGHT_GRAY_WAVES_SEAGLASS = BLOCKS.register("light_gray_waves_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> LIME_BUBBLES_SEAGLASS = BLOCKS.register("lime_bubbles_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> LIME_SEAGLASS = BLOCKS.register("lime_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> LIME_SMOOTH_SEAGLASS = BLOCKS.register("lime_smooth_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> LIME_WAVES_SEAGLASS = BLOCKS.register("lime_waves_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> MAGENTA_BUBBLES_SEAGLASS = BLOCKS.register("magenta_bubbles_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> MAGENTA_SEAGLASS = BLOCKS.register("magenta_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> MAGENTA_SMOOTH_SEAGLASS = BLOCKS.register("magenta_smooth_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> MAGENTA_WAVES_SEAGLASS = BLOCKS.register("magenta_waves_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> ORANGE_BUBBLES_SEAGLASS = BLOCKS.register("orange_bubbles_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> ORANGE_SEAGLASS = BLOCKS.register("orange_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> ORANGE_SMOOTH_SEAGLASS = BLOCKS.register("orange_smooth_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> ORANGE_WAVES_SEAGLASS = BLOCKS.register("orange_waves_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> PINK_BUBBLES_SEAGLASS = BLOCKS.register("pink_bubbles_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> PINK_SEAGLASS = BLOCKS.register("pink_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> PINK_SMOOTH_SEAGLASS = BLOCKS.register("pink_smooth_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> PINK_WAVES_SEAGLASS = BLOCKS.register("pink_waves_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> PURPLE_BUBBLES_SEAGLASS = BLOCKS.register("purple_bubbles_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> PURPLE_SEAGLASS = BLOCKS.register("purple_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> PURPLE_SMOOTH_SEAGLASS = BLOCKS.register("purple_smooth_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> PURPLE_WAVES_SEAGLASS = BLOCKS.register("purple_waves_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> RED_BUBBLES_SEAGLASS = BLOCKS.register("red_bubbles_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> RED_SEAGLASS = BLOCKS.register("red_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> RED_SMOOTH_SEAGLASS = BLOCKS.register("red_smooth_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> RED_WAVES_SEAGLASS = BLOCKS.register("red_waves_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> WHITE_BUBBLES_SEAGLASS = BLOCKS.register("white_bubbles_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> WHITE_SEAGLASS = BLOCKS.register("white_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> WHITE_SMOOTH_SEAGLASS = BLOCKS.register("white_smooth_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> WHITE_WAVES_SEAGLASS = BLOCKS.register("white_waves_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> YELLOW_BUBBLES_SEAGLASS = BLOCKS.register("yellow_bubbles_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> YELLOW_SEAGLASS = BLOCKS.register("yellow_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> YELLOW_SMOOTH_SEAGLASS = BLOCKS.register("yellow_smooth_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));
    public static final DeferredBlock<Block> YELLOW_WAVES_SEAGLASS = BLOCKS.register("yellow_waves_seaglass", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.GLASS).noOcclusion()));

    public static final DeferredBlock<Block> GAPPER_PANEL_OAK = BLOCKS.register("gapper_panel_oak", () -> new Block(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.STONE).noOcclusion()));

    public static final DeferredBlock<HedgeBlock> HEDGE = BLOCKS.register("hedge", () -> new HedgeBlock(Properties.of().strength(4.0f).requiresCorrectToolForDrops().sound(SoundType.WOOD).noOcclusion()));

    public static final DeferredBlock<Block> HEDGE_SPROUTS = BLOCKS.register("hedge_sprouts", () -> new HedgeSprouts(Block.Properties.ofFullCopy(Blocks.WHEAT)));

    static {
        registerGradientBlocks(Blocks.WHITE_CONCRETE, GradientConcreteBlock::new, ALL_CONCRETE_BLOCKS::add);
        registerGradientBlocks(Blocks.WHITE_TERRACOTTA, GradientTerracottaBlock::new, ALL_TERRACOTTA_BLOCKS::add);
        registerGradientBlocks(Blocks.WHITE_WOOL, GradientWoolBlock::new, ALL_WOOL_BLOCKS::add);
        registerGradientBlocks(Blocks.WHITE_STAINED_GLASS, GradientStainedGlassBlock::new, ALL_STAINED_GLASS_BLOCKS::add);
        registerGradientBlocks(Blocks.WHITE_CONCRETE_POWDER, GradientConcretePowderBlock::new, ALL_CONCRETE_POWDER_BLOCKS::add);
    }

    private static <T extends Block & IGradientBlock> void registerGradientBlocks(Block block, GradientBlockBuilder<T> builder, Consumer<DeferredBlock<? extends IGradientBlock>> adder) {
        List<DyeColor> secondaryColors = new ArrayList<>(List.of(DyeColor.values()));
        for (final DyeColor color1 : DyeColor.values()) {
            for (final DyeColor color2 : secondaryColors) {
                if (color1 != color2) {
                    final String blockName = BuiltInRegistries.BLOCK.getKey(block).getPath().replace("white_", "");
                    final String fullName = String.format("%s_%s_%s", color1.getName(), color2.getName(), blockName);
                    DeferredBlock<? extends IGradientBlock> gradientBlock = BLOCKS.register(fullName, () -> builder.create(block.properties(), color1, color2, color -> "%s_%s".formatted(color.getName(), blockName)));
                    adder.accept(gradientBlock);
                    ALL_GRADIENT_BLOCKS.add(gradientBlock);
                }
            }
            secondaryColors.remove(color1);
        }
    }

    public static Collection<DeferredBlock<? extends IGradientBlock>> getAllGradientBlocks() {
        return ALL_GRADIENT_BLOCKS;
    }

    public static Collection<DeferredBlock<? extends IGradientBlock>> getAllGradientConcreteBlocks() {
        return ALL_CONCRETE_BLOCKS;
    }

    private static <T extends Block> DeferredBlock<T> registerLeaf(String name, java.util.function.Supplier<T> block) {
        DeferredBlock<T> ret = BLOCKS.register(name, block);
        LEAVES.add(ret);
        return ret;
    }

    // Insane List of Leaves
    public static final DeferredBlock<Block> ACACIA_LEAVES = registerLeaf("acacia_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ALPHA_OAK_LEAVES = registerLeaf("alpha_oak_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ANCIENT_LEAVES = registerLeaf("ancient_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ANCIENT_OAK_LEAVES = registerLeaf("ancient_oak_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> APICOT_LEAVES = registerLeaf("apicot_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> APPLE_LEAVES = registerLeaf("apple_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> APRICORN_LEAVES = registerLeaf("apricorn_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ARAUCARIA_LEAVES = registerLeaf("araucaria_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ASHEN_LEAVES = registerLeaf("ashen_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ASPEAR_LEAVES = registerLeaf("aspear_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ASPEN2_LEAVES = registerLeaf("aspen2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ASPEN_LEAVES = registerLeaf("aspen_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> AUREL_LEAVES = registerLeaf("aurel_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> AUREL_LEAVES_MIRRORED = registerLeaf("aurel_leaves_mirrored", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> AURUM_LEAVES = registerLeaf("aurum_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> AZALEA_LEAVES = registerLeaf("azalea_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BAMBOO_LEAVES = registerLeaf("bamboo_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BAOBAB2_LEAVES = registerLeaf("baobab2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BAOBAB3_LEAVES = registerLeaf("baobab3_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BAOBAB_LEAVES = registerLeaf("baobab_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BAYBERRY_LEAVES = registerLeaf("bayberry_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BIRCH_LEAVES = registerLeaf("birch_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BLACKWOOD_LEAVES = registerLeaf("blackwood_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BLIGHTED_BALSA_LEAVES = registerLeaf("blighted_balsa_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BLUE_ARCHWOOD_LEAVES = registerLeaf("blue_archwood_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BLUE_ARCHWOOD_LEAVES_1 = registerLeaf("blue_archwood_leaves_1", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BLUE_ARCHWOOD_LEAVES_2 = registerLeaf("blue_archwood_leaves_2", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BLUE_BLOSSOM_LEAVES = registerLeaf("blue_blossom_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BLUE_ENCHANTED_LEAVES = registerLeaf("blue_enchanted_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BLUE_MAGNOLIA_LEAVES = registerLeaf("blue_magnolia_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BLUE_ROSEROOT_LEAVES = registerLeaf("blue_roseroot_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BLUE_SPRUCE_LEAVES = registerLeaf("blue_spruce_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BLUE_WISTERIA2_LEAVES = registerLeaf("blue_wisteria2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BLUE_WISTERIA2_LEAVES_TOP = registerLeaf("blue_wisteria2_leaves_top", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BLUE_WISTERIA_LEAVES = registerLeaf("blue_wisteria_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BRIMWOOD_LEAVES = registerLeaf("brimwood_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BROWN_AUTUMNAL_LEAVES = registerLeaf("brown_autumnal_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BROWN_BIRCH_LEAVES = registerLeaf("brown_birch_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BROWN_OAK_LEAVES = registerLeaf("brown_oak_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BROWN_ZELKOVA_LEAVES = registerLeaf("brown_zelkova_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BUDDING_PEONY_LEAVES = registerLeaf("budding_peony_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BUDDING_PEONY_LEAVES_VARIANT = registerLeaf("budding_peony_leaves_variant", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> BUDDING_PEONY_LEAVES_VARIANT2 = registerLeaf("budding_peony_leaves_variant2", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CAVE_BUSH_LEAVES_1 = registerLeaf("cave_bush_leaves_1", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CAVE_BUSH_LEAVES_2 = registerLeaf("cave_bush_leaves_2", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CAVE_BUSH_LEAVES_3 = registerLeaf("cave_bush_leaves_3", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CAVE_BUSH_LEAVES_4 = registerLeaf("cave_bush_leaves_4", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CEDAR_LEAVES = registerLeaf("cedar_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CHARTI_LEAVES = registerLeaf("charti_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CHEERFUL_PLUM_LEAVES = registerLeaf("cheerful_plum_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CHERI_LEAVES = registerLeaf("cheri_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CHERRY_LEAVES = registerLeaf("cherry_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CHESTO_LEAVES = registerLeaf("chesto_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CHILAN_LEAVES = registerLeaf("chilan_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CHOPLE_LEAVES = registerLeaf("chople_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CIKA_LEAVES = registerLeaf("cika_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CINNAMON_LEAVES = registerLeaf("cinnamon_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> COCONUT_LEAVES = registerLeaf("coconut_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> COLBUR_LEAVES = registerLeaf("colbur_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CONBERRY_LEAVES = registerLeaf("conberry_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CORNN_LEAVES = registerLeaf("cornn_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CRUDEROOT_LEAVES = registerLeaf("cruderoot_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CRYSTAL_FRUIT_LEAVES = registerLeaf("crystal_fruit_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CRYSTAL_LEAVES = registerLeaf("crystal_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CYPRESS2_LEAVES = registerLeaf("cypress2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CYPRESS3_LEAVES = registerLeaf("cypress3_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CYPRESS4_LEAVES = registerLeaf("cypress4_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CYPRESS5_LEAVES = registerLeaf("cypress5_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CYPRESS6_LEAVES = registerLeaf("cypress6_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CYPRESS7_LEAVES = registerLeaf("cypress7_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> CYPRESS_LEAVES = registerLeaf("cypress_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> DARK_OAK_LEAVES = registerLeaf("dark_oak_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> DEAD2_LEAVES = registerLeaf("dead2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> DEAD_LEAVES = registerLeaf("dead_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> DEAD_PINE_LEAVES = registerLeaf("dead_pine_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> DECORATED_HOLIDAY_LEAVES = registerLeaf("decorated_holiday_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> DESERT_BLOSSOM_LEAVES = registerLeaf("desert_blossom_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> DRAGON_TREE_LEAVES = registerLeaf("dragon_tree_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> DRAGONS_BLOOD_LEAVES = registerLeaf("dragons_blood_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> DURIAN_LEAVES = registerLeaf("durian_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> EBONY_LEAVES = registerLeaf("ebony_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ELDER_LEAVES = registerLeaf("elder_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> EMPYREAL_LEAVES = registerLeaf("empyreal_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ENCHANTED_BIRCH_LEAVES = registerLeaf("enchanted_birch_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ENIGMA_LEAVES = registerLeaf("enigma_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> EUCALYPTUS_LEAVES = registerLeaf("eucalyptus_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> FIG_LEAVES = registerLeaf("fig_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> FIR2_LEAVES = registerLeaf("fir2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> FIR3_LEAVES = registerLeaf("fir3_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> FIR4_LEAVES = registerLeaf("fir4_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> FIR_LEAVES = registerLeaf("fir_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> FIRECRACKER_LEAVES = registerLeaf("firecracker_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> FLOWERING_AZALEA_LEAVES = registerLeaf("flowering_azalea_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> FLOWERING_BAOBAB_LEAVES = registerLeaf("flowering_baobab_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> FLOWERING_BLUE_ROSEROOT_LEAVES = registerLeaf("flowering_blue_roseroot_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> FLOWERING_INDIGO_JACARANDA_LEAVES = registerLeaf("flowering_indigo_jacaranda_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> FLOWERING_IRONWOOD_LEAVES = registerLeaf("flowering_ironwood_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> FLOWERING_JACARANDA_LEAVES = registerLeaf("flowering_jacaranda_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> FLOWERING_OAK_LEAVES = registerLeaf("flowering_oak_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> FLOWERING_ORCHARD_LEAVES = registerLeaf("flowering_orchard_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> FLOWERING_PALO_VERDE_LEAVES = registerLeaf("flowering_palo_verde_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> FLOWERING_ROSEROOT_LEAVES = registerLeaf("flowering_roseroot_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> FLOWERING_SKYRIS_LEAVES = registerLeaf("flowering_skyris_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> FLOWERING_SPIRIT_LEAVES = registerLeaf("flowering_spirit_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> FROST_WISTERIA_LEAVES = registerLeaf("frost_wisteria_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> FROSTY_FIR_LEAVES = registerLeaf("frosty_fir_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> FROSTY_REDWOOD_LEAVES = registerLeaf("frosty_redwood_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> GHAF_LEAVES = registerLeaf("ghaf_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> GLACIAN_LEAVES = registerLeaf("glacian_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> GOLDEN_LARCH_LEAVES = registerLeaf("golden_larch_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> GOLDEN_LARCH_LEAVES_CONE = registerLeaf("golden_larch_leaves_cone", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> GOLDEN_OAK_LEAVES = registerLeaf("golden_oak_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> GREEN_APPLE_SKYRIS_LEAVES = registerLeaf("green_apple_skyris_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> GREEN_ARCHWOOD_LEAVES = registerLeaf("green_archwood_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> GREEN_ARCHWOOD_LEAVES_1 = registerLeaf("green_archwood_leaves_1", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> GREEN_ARCHWOOD_LEAVES_2 = registerLeaf("green_archwood_leaves_2", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> GREEN_ENCHANTED_LEAVES = registerLeaf("green_enchanted_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> GREPA_LEAVES = registerLeaf("grepa_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> GRONGLE_LEAVES = registerLeaf("grongle_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> HABAN_LEAVES = registerLeaf("haban_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> HAWBERRY_LEAVES = registerLeaf("hawberry_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> HELLBARK_LEAVES = registerLeaf("hellbark_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> HEMLOCK_LEAVES = registerLeaf("hemlock_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> HIBISCUS_LEAVES = registerLeaf("hibiscus_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> HOLIDAY_LEAVES = registerLeaf("holiday_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> HOLLY_BERRY2_LEAVES = registerLeaf("holly_berry2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> HOLLY_BERRY_LEAVES = registerLeaf("holly_berry_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> HOLLY_LEAVES = registerLeaf("holly_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> HOPO_LEAVES = registerLeaf("hopo_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> HYDRANGEA_LEAVES = registerLeaf("hydrangea_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> HYDRANGEA_LEAVES_VARIANT = registerLeaf("hydrangea_leaves_variant", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> HYDRANGEA_LEAVES_VARIANT2 = registerLeaf("hydrangea_leaves_variant2", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> HYDRANGEA_LEAVES_VARIANT3 = registerLeaf("hydrangea_leaves_variant3", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> INDIGO_JACARANDA_LEAVES = registerLeaf("indigo_jacaranda_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> INK_BUSH_LEAVES = registerLeaf("ink_bush_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> IRONWOOD_LEAVES = registerLeaf("ironwood_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> JABOCA_LEAVES = registerLeaf("jaboca_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> JABOTICABA_LEAVES = registerLeaf("jaboticaba_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> JACARANDA2_LEAVES = registerLeaf("jacaranda2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> JACARANDA3_LEAVES = registerLeaf("jacaranda3_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> JACARANDA4_LEAVES = registerLeaf("jacaranda4_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> JACARANDA_LEAVES = registerLeaf("jacaranda_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> JACARANDA_LEAVES_BUDDING_FLOWERS = registerLeaf("jacaranda_leaves_budding_flowers", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> JACARANDA_LEAVES_FLOWERS = registerLeaf("jacaranda_leaves_flowers", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> JACARANDA_LEAVES_VARIANT = registerLeaf("jacaranda_leaves_variant", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> JAPANESE_MAPLE_LEAVES = registerLeaf("japanese_maple_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> JAPANESE_MAPLE_LEAVES_DARK = registerLeaf("japanese_maple_leaves_dark", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> JAPANESE_MAPLE_LEAVES_GREEN = registerLeaf("japanese_maple_leaves_green", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> JOSHUA_LEAVES = registerLeaf("joshua_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> JUNGLE_LEAVES = registerLeaf("jungle_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> JUNGLE_PALM_LEAVES = registerLeaf("jungle_palm_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> JUNIPER_LEAVES = registerLeaf("juniper_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> KAPOK_LEAVES = registerLeaf("kapok_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> KEBIA_LEAVES = registerLeaf("kebia_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> KEE_LEAVES = registerLeaf("kee_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> KIWI_LEAVES = registerLeaf("kiwi_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> LACUGROVE_LEAVES = registerLeaf("lacugrove_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> LANSAT_LEAVES = registerLeaf("lansat_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> LARCH2_LEAVES = registerLeaf("larch2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> LARCH_LEAVES = registerLeaf("larch_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> LARCH_LEAVES_CONE = registerLeaf("larch_leaves_cone", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> LAVENDER_BLOSSOM_LEAVES = registerLeaf("lavender_blossom_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> LAVENDER_WISTERIA_LEAVES = registerLeaf("lavender_wisteria_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> LUCERNIA_LEAVES_1 = registerLeaf("lucernia_leaves_1", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> LUCERNIA_LEAVES_2 = registerLeaf("lucernia_leaves_2", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> LUCERNIA_LEAVES_3 = registerLeaf("lucernia_leaves_3", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> LUCERNIA_LEAVES_4 = registerLeaf("lucernia_leaves_4", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> LUNAR_LEAVES = registerLeaf("lunar_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> LYCHEE_LEAVES = registerLeaf("lychee_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> MAGIC_LEAVES = registerLeaf("magic_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> MAGIC_LEAVES_ALT = registerLeaf("magic_leaves_alt", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> MAGNOLIA_LEAVES = registerLeaf("magnolia_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> MAGO_LEAVES = registerLeaf("mago_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> MAHOGANY3_LEAVES = registerLeaf("mahogany3_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> MAHOGANY_LEAVES = registerLeaf("mahogany_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> MANGO_LEAVES = registerLeaf("mango_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> MANGOSTEEN_LEAVES = registerLeaf("mangosteen_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> MANGROVE_LEAVES = registerLeaf("mangrove_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> MAPLE2_LEAVES = registerLeaf("maple2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> MAPLE3_LEAVES = registerLeaf("maple3_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> MAPLE4_LEAVES = registerLeaf("maple4_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> MAPLE_LEAVES = registerLeaf("maple_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> MAPLE_LEAVES_VARIANT = registerLeaf("maple_leaves_variant", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> MAPLE_LEAVES_VARIANT2 = registerLeaf("maple_leaves_variant2", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> MAUVE_LEAVES = registerLeaf("mauve_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> MAUVE_LEAVES_FLOWERING = registerLeaf("mauve_leaves_flowering", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> MAUVE_LEAVES_FLOWERING_2 = registerLeaf("mauve_leaves_flowering_2", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> MAUVE_LEAVES_FLOWERING_3 = registerLeaf("mauve_leaves_flowering_3", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> MENRIL_LEAVES_FANCY = registerLeaf("menril_leaves_fancy", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> MICLE_LEAVES = registerLeaf("micle_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> MOODY_PLUM_LEAVES = registerLeaf("moody_plum_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> MOTHER_AUREL_LEAVES = registerLeaf("mother_aurel_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> NANAB_LEAVES = registerLeaf("nanab_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> NORTHLAND_LEAVES = registerLeaf("northland_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> NORTHLAND_LEAVES_SNOWY = registerLeaf("northland_leaves_snowy", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> NUGGETY_AURUM_LEAVES = registerLeaf("nuggety_aurum_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> OAK_LEAVES = registerLeaf("oak_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> OLIVE_LEAVES = registerLeaf("olive_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ORAN_LEAVES = registerLeaf("oran_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ORANGE2_LEAVES = registerLeaf("orange2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ORANGE_AUTUMNAL_LEAVES = registerLeaf("orange_autumnal_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ORANGE_BIRCH_LEAVES = registerLeaf("orange_birch_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ORANGE_BLOSSOM_LEAVES = registerLeaf("orange_blossom_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ORANGE_LEAVES = registerLeaf("orange_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ORANGE_LEAVES_FLOWERING = registerLeaf("orange_leaves_flowering", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ORANGE_LEAVES_FRUITING = registerLeaf("orange_leaves_fruiting", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ORANGE_MAPLE2_LEAVES = registerLeaf("orange_maple2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ORANGE_MAPLE3_LEAVES = registerLeaf("orange_maple3_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ORANGE_MAPLE4_LEAVES = registerLeaf("orange_maple4_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ORANGE_MAPLE5_LEAVES = registerLeaf("orange_maple5_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ORANGE_MAPLE_LEAVES = registerLeaf("orange_maple_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ORANGE_OAK_LEAVES = registerLeaf("orange_oak_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ORANGE_SPRUCE_LEAVES = registerLeaf("orange_spruce_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ORCHARD_LEAVES = registerLeaf("orchard_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ORIGIN_LEAVES = registerLeaf("origin_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PALE_LEAVES = registerLeaf("pale_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PALE_OAK_LEAVES = registerLeaf("pale_oak_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PALM2_LEAVES = registerLeaf("palm2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PALM3_LEAVES = registerLeaf("palm3_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PALM_FRONDS = registerLeaf("palm_fronds", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PALM_LEAVES = registerLeaf("palm_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PALO_VERDE2_LEAVES = registerLeaf("palo_verde2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PALO_VERDE_LEAVES = registerLeaf("palo_verde_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PART_BLUE_WISTERIA_LEAVES = registerLeaf("part_blue_wisteria_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PART_PINK_WISTERIA_LEAVES = registerLeaf("part_pink_wisteria_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PART_PURPLE_WISTERIA_LEAVES = registerLeaf("part_purple_wisteria_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PART_WHITE_WISTERIA_LEAVES = registerLeaf("part_white_wisteria_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PEACH2_LEAVES = registerLeaf("peach2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PEACH_LEAVES = registerLeaf("peach_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PEAR_LEAVES = registerLeaf("pear_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PEONY_LEAVES = registerLeaf("peony_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PERSIM_LEAVES = registerLeaf("persim_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PERSIMMON_LEAVES = registerLeaf("persimmon_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PINE2_LEAVES = registerLeaf("pine2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PINE3_LEAVES = registerLeaf("pine3_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PINE4_LEAVES = registerLeaf("pine4_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PINE5_LEAVES = registerLeaf("pine5_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PINE_LEAVES = registerLeaf("pine_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PINK_MAGNOLIA_LEAVES = registerLeaf("pink_magnolia_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PINK_WISTERIA2_LEAVES = registerLeaf("pink_wisteria2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PINK_WISTERIA2_LEAVES_TOP = registerLeaf("pink_wisteria2_leaves_top", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PINK_WISTERIA_LEAVES = registerLeaf("pink_wisteria_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PLUM_LEAVES = registerLeaf("plum_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PREAM_LEAVES = registerLeaf("pream_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PURPLE_ARCHWOOD_LEAVES = registerLeaf("purple_archwood_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PURPLE_ARCHWOOD_LEAVES_1 = registerLeaf("purple_archwood_leaves_1", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PURPLE_ARCHWOOD_LEAVES_2 = registerLeaf("purple_archwood_leaves_2", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PURPLE_WISTERIA2_LEAVES = registerLeaf("purple_wisteria2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PURPLE_WISTERIA2_LEAVES_TOP = registerLeaf("purple_wisteria2_leaves_top", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PURPLE_WISTERIA_LEAVES = registerLeaf("purple_wisteria_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> PYTHADENDRON_LEAVES = registerLeaf("pythadendron_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> QUALOT_LEAVES = registerLeaf("qualot_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> RAINBOW_BIRCH_LEAVES = registerLeaf("rainbow_birch_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> RAINBOW_EUCALYPTUS2_LEAVES = registerLeaf("rainbow_eucalyptus2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> RAINBOW_EUCALYPTUS_LEAVES = registerLeaf("rainbow_eucalyptus_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> RAMBOUTAN_LEAVES = registerLeaf("ramboutan_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> RED_ARCHWOOD_LEAVES = registerLeaf("red_archwood_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> RED_ARCHWOOD_LEAVES_1 = registerLeaf("red_archwood_leaves_1", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> RED_ARCHWOOD_LEAVES_2 = registerLeaf("red_archwood_leaves_2", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> RED_AUTUMNAL_LEAVES = registerLeaf("red_autumnal_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> RED_BIRCH_LEAVES = registerLeaf("red_birch_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> RED_BLOSSOM_LEAVES = registerLeaf("red_blossom_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> RED_MAPLE2_LEAVES = registerLeaf("red_maple2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> RED_MAPLE3_LEAVES = registerLeaf("red_maple3_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> RED_MAPLE4_LEAVES = registerLeaf("red_maple4_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> RED_MAPLE5_LEAVES = registerLeaf("red_maple5_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> RED_MAPLE_LEAVES = registerLeaf("red_maple_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> RED_OAK_LEAVES = registerLeaf("red_oak_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> RED_SPRUCE_LEAVES = registerLeaf("red_spruce_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> REDWOOD2_LEAVES = registerLeaf("redwood2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> REDWOOD3_LEAVES = registerLeaf("redwood3_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> REDWOOD4_LEAVES = registerLeaf("redwood4_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> REDWOOD5_LEAVES = registerLeaf("redwood5_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> REDWOOD_LEAVES = registerLeaf("redwood_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> RINDO_LEAVES = registerLeaf("rindo_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> RIPE_BAOBAB_LEAVES = registerLeaf("ripe_baobab_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> RIPE_ORCHARD_LEAVES = registerLeaf("ripe_orchard_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ROSE_WISTERIA_LEAVES = registerLeaf("rose_wisteria_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ROSEROOT_LEAVES = registerLeaf("roseroot_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> RUBBER2_LEAVES = registerLeaf("rubber2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> RUBBER_LEAVES = registerLeaf("rubber_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> RUBEUS_LEAVES = registerLeaf("rubeus_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> SAKURA_LEAVES = registerLeaf("sakura_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> SAXAUL_LEAVES = registerLeaf("saxaul_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> SCARLET_LEAVES = registerLeaf("scarlet_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> SEA_SHRUB_LEAVES = registerLeaf("sea_shrub_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> SEQUOIA_LEAVES = registerLeaf("sequoia_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> SHADOW_BERRY_LEAVES = registerLeaf("shadow_berry_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> SHUCA_LEAVES = registerLeaf("shuca_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> SILVER_BIRCH_LEAVES = registerLeaf("silver_birch_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> SILVER_MAPLE_LEAVES = registerLeaf("silver_maple_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> SITRUS_LEAVES = registerLeaf("sitrus_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> SKYRIS_LEAVES = registerLeaf("skyris_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> SKYROOT_LEAVES = registerLeaf("skyroot_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> SMOGSTEM_LEAVES = registerLeaf("smogstem_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> SNOWBLOSSOM_LEAVES = registerLeaf("snowblossom_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> SNOWY_FIR_LEAVES = registerLeaf("snowy_fir_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> SOCOTRA_LEAVES = registerLeaf("socotra_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> SPIRIT_LEAVES = registerLeaf("spirit_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> SPRUCE_LEAVES = registerLeaf("spruce_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> STARF_LEAVES = registerLeaf("starf_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> STARLIGHT_MANGROVE_LEAVES = registerLeaf("starlight_mangrove_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> SUGI_LEAVES = registerLeaf("sugi_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> SUNROOT_LEAVES = registerLeaf("sunroot_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> SWAMP_CYPRESS_LEAVES = registerLeaf("swamp_cypress_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> TAMATO_LEAVES = registerLeaf("tamato_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> TANGA_LEAVES = registerLeaf("tanga_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> TENANEA_LEAVES = registerLeaf("tenanea_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> TORREYA_LEAVES = registerLeaf("torreya_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> TROPICAL_LEAVES = registerLeaf("tropical_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> TWISTED_LEAVES = registerLeaf("twisted_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> UMBRAN_LEAVES = registerLeaf("umbran_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> VEILED_LEAVES = registerLeaf("veiled_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> WALNUT_LEAVES = registerLeaf("walnut_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> WEPEAR_LEAVES = registerLeaf("wepear_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> WHITE_MAGNOLIA_LEAVES = registerLeaf("white_magnolia_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> WHITE_MANGROVE_LEAVES = registerLeaf("white_mangrove_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> WHITE_SAKURA_LEAVES = registerLeaf("white_sakura_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> WHITE_WISTERIA2_LEAVES = registerLeaf("white_wisteria2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> WHITE_WISTERIA2_LEAVES_TOP = registerLeaf("white_wisteria2_leaves_top", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> WHITE_WISTERIA_LEAVES = registerLeaf("white_wisteria_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> WIGGLEWOOD_LEAVES = registerLeaf("wigglewood_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> WILLOW2_LEAVES = registerLeaf("willow2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> WILLOW3_LEAVES = registerLeaf("willow3_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> WILLOW4_LEAVES = registerLeaf("willow4_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> WILLOW5_LEAVES = registerLeaf("willow5_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> WILLOW6_LEAVES = registerLeaf("willow6_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> WILLOW7_LEAVES = registerLeaf("willow7_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> WILLOW7_LEAVES_TOP = registerLeaf("willow7_leaves_top", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> WILLOW_LEAVES = registerLeaf("willow_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> WISTERIA2_LEAVES = registerLeaf("wisteria2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> WISTERIA_LEAVES = registerLeaf("wisteria_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> YAGROOT_LEAVES = registerLeaf("yagroot_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> YELLOW_ARCHWOOD_LEAVES = registerLeaf("yellow_archwood_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> YELLOW_ARCHWOOD_LEAVES_1 = registerLeaf("yellow_archwood_leaves_1", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> YELLOW_ARCHWOOD_LEAVES_2 = registerLeaf("yellow_archwood_leaves_2", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> YELLOW_ASPEN_LEAVES = registerLeaf("yellow_aspen_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> YELLOW_AUTUMNAL_LEAVES = registerLeaf("yellow_autumnal_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> YELLOW_BIRCH_LEAVES = registerLeaf("yellow_birch_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> YELLOW_BLOSSOM_LEAVES = registerLeaf("yellow_blossom_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> YELLOW_MAPLE2_LEAVES = registerLeaf("yellow_maple2_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> YELLOW_MAPLE3_LEAVES = registerLeaf("yellow_maple3_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> YELLOW_MAPLE4_LEAVES = registerLeaf("yellow_maple4_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> YELLOW_MAPLE_LEAVES = registerLeaf("yellow_maple_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> YELLOW_SAKURA_LEAVES = registerLeaf("yellow_sakura_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> YELLOW_SPRUCE_LEAVES = registerLeaf("yellow_spruce_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> YUCCA_PALM_LEAVES = registerLeaf("yucca_palm_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));
    public static final DeferredBlock<Block> ZELKOVA_LEAVES = registerLeaf("zelkova_leaves", () -> new Block(Properties.of().strength(0.2f).sound(SoundType.GRASS).noOcclusion()));

    @FunctionalInterface
    private interface GradientBlockBuilder<T extends Block & IGradientBlock> {
        T create(Properties properties, DyeColor firstColor, DyeColor secondColor, Function<DyeColor, String> textureNameMapper);
    }
}