# suppress inspection "UnusedProperty"
matchItems=enchanted_book
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
stackSize=1-64
tile=curse_of_vanishing
enchantmentIDs=vanishing_curse