# suppress inspection "UnusedProperty"
matchItems=enchanted_book
# suppress inspection "UnusedProperty"
stackSize=1-64
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
tile=feather_falling
enchantmentIDs=feather_falling