# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
type=item
matchItems=painting
model=optifine/cit/items/paintings/backyard.json
components.minecraft\:entity_data.variant=minecraft:backyard