# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
type=item
matchItems=painting
# suppress inspection "UnusedProperty"
model=optifine/cit/items/paintings/fighters.json
# suppress inspection "UnusedProperty"
components.minecraft\:entity_data.variant=minecraft:fighters