# suppress inspection "UnusedProperty"
type=item
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
matchItems=painting
# suppress inspection "UnusedProperty"
model=optifine/cit/items/paintings/graham.json
components.minecraft\:entity_data.variant=minecraft:graham