# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
type=item
matchItems=painting
model=optifine/cit/items/paintings/pigscene.json
# suppress inspection "UnusedProperty"
components.minecraft\:entity_data.variant=minecraft:pigscene