# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
type=item
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
matchItems=painting
model=optifine/cit/items/paintings/prairie_ride.json
components.minecraft\:entity_data.variant=minecraft:prairie_ride