# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
type=item
matchItems=painting
# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
model=optifine/cit/items/paintings/skeleton.json
components.minecraft\:entity_data.variant=minecraft:skeleton