# suppress inspection "UnusedProperty"
# suppress inspection "UnusedProperty"
type=item
# suppress inspection "UnusedProperty"
matchItems=painting
model=optifine/cit/items/paintings/tides.json
# suppress inspection "UnusedProperty"
components.minecraft\:entity_data.variant=minecraft:tides